# Import Library

In [4]:
import numpy as np

# Assign Data

In [5]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

# Mean Absolute Error

### Without Numpy

In [6]:
def mae(y_true, y_predicted):
  total_error = 0
  for yt,yp in zip(y_true,y_predicted):
    total_error += abs(yt-yp)
  print("Total error:",total_error)
  mae = total_error / len(y_true)
  print("Mean Absolute Error:",mae)
  return mae

In [7]:
mae(y_true,y_predicted)

Total error: 2.5
Mean Absolute Error: 0.5


0.5

### With Numpy

In [8]:
np.sum(np.abs(y_predicted-y_true))

2.5

In [9]:
np.mean(np.abs(y_predicted-y_true))

0.5

# Mean Square Error

### Without Numpy

In [35]:
def mse(y_true,y_predicted):
  total_error=0
  for yt,yp in zip(y_true,y_predicted):
    total_error += np.square(yt-yp)
  print("Total error:",total_error)
  mse = total_error / len(y_true)
  print("Mean Square Error:",mse)
  return mse

In [36]:
mse(y_true,y_predicted)

Total error: 1.83
Mean Square Error: 0.366


0.366

### With Numpy

In [11]:
np.sum(np.square(y_predicted-y_true))

1.83

In [10]:
np.mean(np.square(y_predicted-y_true))

0.366

# Log loss or binary cross entropy

### Firstly we need to replace values close to it

In [18]:
np.log(y_predicted)

<ipython-input-18-d8d657355a01>:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf, -inf,   0.])

In [12]:
eplison = 1e-15

In [16]:
y_predicted

array([1, 1, 0, 0, 1])

In [13]:
y_predicted_new = [max(i,eplison) for i in y_predicted] # list comprehension in python
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [14]:
y_predicted_new = [min(i,1-eplison) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [23]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

## Calculate Log loss

In [30]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [33]:
def log_loss(y_true,y_predicted):
  eplison = 1e-15
  y_predicted_new = [max(i,eplison) for i in y_predicted]
  y_predicted_new = [min(i,1-eplison) for i in y_predicted_new]
  y_predicted_new = np.array(y_predicted_new)
  return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [34]:
log_loss(y_true,y_predicted)

17.2696280766844